-- return {
--   "yetone/avante.nvim",
--   event = "VeryLazy",
--   lazy = false,
--   opts = {
--     -- add any opts here
--     -- for example
--
--     windows = {
--       position = "left", -- the position of the sidebar
--       wrap = true, -- similar to vim.o.wrap
--       width = 30, -- default % based on available width
--       sidebar_header = {
--         align = "center", -- left, center, right for title
--         rounded = true,
--       },
--     },
--     dual_boost = {
--       enabled = false,
--       first_provider = "claude",
--       second_provider = "openai",
--       prompt = "Based on the two reference outputs below, generate a response that incorporates elements from both but reflects your own judgment and unique perspective. Do not provide any explanation, just give the response directly. Reference Output 1: [{{provider1_output}}], Reference Output 2: [{{provider2_output}}]",
--       timeout = 60000, -- Timeout in milliseconds
--     },
--
--     providers = {
--       -- "claude",
--       claude = {
--         endpoint = "https://api.anthropic.com",
--         model = "claude-sonnet-4-20250514",
--         extra_request_body = {
--           temperature = 0,
--           max_tokens = 4096,
--         },
--       },
--       -- "openai",
--       -- "openai_gpt4",,
--       -- "openai_gpt4_32k",
--     },
--   },
--   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--   build = "make",
--   -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
--   dependencies = {
--     "stevearc/dressing.nvim",
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     --- The below dependencies are optional,
--     "echasnovski/mini.pick", -- for file_selector provider mini.pick
--     "nvim-telescope/telescope.nvim", -- for file_selector provider telescope
--     "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
--     "ibhagwan/fzf-lua", -- for file_selector provider fzf
--     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
--     -- "zbirenbaum/copilot.lua", -- for providers='copilot'
--     {
--       -- support for image pasting
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         -- recommended settings
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           -- required for Windows users
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       -- Make sure to set this up properly if you have lazy=true
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
-- }
